#!/usr/bin/env node
// Kokeba upscale — bring page art up to print resolution (>=300 DPI at the book's trim).
// gpt-image caps at ~1024-1536px (≈120-180 DPI at 8.5"), which KDP rejects. This upscales
// every page to the required pixel count. Default engine = sharp (Lanczos3); swap in an AI
// upscaler (Real-ESRGAN / Replicate) by replacing the `upscaleFile` body.
//
// Usage:
//   node scripts/upscale/upscale-art.mjs <book-dir> [--dpi 300] [--force]
// Writes hi-res PNGs in place (originals are regenerated by the illustration stage).

import fs from "node:fs";
import path from "node:path";

const bookDir = process.argv[2];
const DPI = Number((process.argv.find((a) => a.startsWith("--dpi=")) || "").split("=")[1] || (process.argv.includes("--dpi") ? process.argv[process.argv.indexOf("--dpi") + 1] : 300));
const FORCE = process.argv.includes("--force");
if (!bookDir) { console.error("Usage: node scripts/upscale/upscale-art.mjs <book-dir> [--dpi 300]"); process.exit(2); }

const L = JSON.parse(fs.readFileSync(path.resolve(bookDir, "layout.json"), "utf8"));
const artDir = path.resolve(bookDir, L.art_dir || "art");
const tm = String(L.trim || "8.5x8.5in").match(/([\d.]+)x([\d.]+)/);
const trimW = tm ? parseFloat(tm[1]) : 8.5;
const bleed = Number(L.bleed_in || 0.125);
const target = Math.ceil((trimW + 2 * bleed) * DPI); // px on the long edge

function pngW(fp) { try { const b = fs.readFileSync(fp).subarray(0, 24); return b[0] === 0x89 ? b.readUInt32BE(16) : 0; } catch { return 0; } }

let sharp;
try { sharp = (await import("sharp")).default; }
catch {
  console.log("\nUpscaling needs the `sharp` image library (not installed).");
  console.log("  Install once:  npm i sharp");
  console.log("  Then re-run this stage. (Or swap in an AI upscaler in upscaleFile().)");
  process.exit(0);
}

async function upscaleFile(fp, toPx) {
  const buf = await sharp(fp).resize(toPx, toPx, { kernel: "lanczos3", fit: "fill" }).png({ compressionLevel: 9 }).toBuffer();
  fs.writeFileSync(fp, buf);
}

const files = [...new Set((L.pages || []).map((p) => p.image).filter(Boolean))];
let done = 0, skipped = 0;
for (const f of files) {
  const fp = path.resolve(artDir, f);
  if (!fs.existsSync(fp)) continue;
  const w = pngW(fp);
  if (!FORCE && w >= target) { skipped++; continue; }
  process.stdout.write(`↑ ${f}: ${w}px -> ${target}px … `);
  await upscaleFile(fp, target);
  console.log("done");
  done++;
}
console.log(`\nUpscaled ${done} page(s) to ${target}px (~${DPI} DPI at ${trimW}in trim); ${skipped} already at-res.`);
